-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-06-02 21:06:49 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on
SPOOL mf_schema_output.txt

-- Group G18
-- student id: 36385379
-- student name: Yongseok Kwon
-- student id: 32527942
-- student name: Nandhika Nelluri



DROP TABLE BOOKING CASCADE CONSTRAINTS 
;

DROP TABLE BOOKING_CHEF CASCADE CONSTRAINTS 
;

DROP TABLE CHEF CASCADE CONSTRAINTS 
;

DROP TABLE CUISINE CASCADE CONSTRAINTS 
;

DROP TABLE CUSTOMER CASCADE CONSTRAINTS 
;

DROP TABLE DECOR_THEME CASCADE CONSTRAINTS 
;

DROP TABLE EVALUATION CASCADE CONSTRAINTS 
;

DROP TABLE MAINTENANCE CASCADE CONSTRAINTS 
;

DROP TABLE ROOM CASCADE CONSTRAINTS 
;

DROP TABLE ROOM_CHARGE_HISTORY CASCADE CONSTRAINTS 
;

DROP TABLE SPECIALITY CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE BOOKING 
    ( 
     booking_id          NUMBER (7)  NOT NULL , 
     cust_id             NUMBER (7)  NOT NULL , 
     book_start_datetime DATE  NOT NULL , 
     book_end_datetime   DATE  NOT NULL , 
     book_n_guest        NUMBER (4)  NOT NULL , 
     book_total_cost     NUMBER (7,2)  NOT NULL , 
     book_paid           CHAR (1)  NOT NULL , 
     room_id             NUMBER (7) , 
     cuisine_type        VARCHAR2 (20) , 
     base_rate_guest     NUMBER (5,2)  NOT NULL , 
     decor_theme_name    VARCHAR2 (20) 
    ) 
;

ALTER TABLE BOOKING 
    ADD 
    CHECK (book_paid IN ('N', 'Y')) 
;

COMMENT ON COLUMN BOOKING.booking_id IS 'A booking ID consisting of 7 digits (surrogate key)' 
;

COMMENT ON COLUMN BOOKING.cust_id IS 'unique identifier of customer (7 digit)' 
;

COMMENT ON COLUMN BOOKING.book_start_datetime IS 'booking start date and time' 
;

COMMENT ON COLUMN BOOKING.book_end_datetime IS 'booking end date and time' 
;

COMMENT ON COLUMN BOOKING.book_n_guest IS 'number of guests (up to 9999)' 
;

COMMENT ON COLUMN BOOKING.book_total_cost IS 'total cost of function in dollors (up to $99999.99)' 
;

COMMENT ON COLUMN BOOKING.book_paid IS 'indicates whether payment has been made (Y-Yes or N-No)' 
;

COMMENT ON COLUMN BOOKING.room_id IS 'unique identifier of function room (up to 7 digits)' 
;

COMMENT ON COLUMN BOOKING.cuisine_type IS 'Type of cuisine - up to 20 characters' 
;

COMMENT ON COLUMN BOOKING.base_rate_guest IS 'booking base rate charge per guest in dollars (up to $999.99)' 
;

COMMENT ON COLUMN BOOKING.decor_theme_name IS 'name of decoration theme (up to 20 letters)' 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_PK PRIMARY KEY ( booking_id ) ;

ALTER TABLE BOOKING 
    ADD CONSTRAINT Booking_UQ UNIQUE ( cust_id , book_start_datetime ) ;

CREATE TABLE BOOKING_CHEF 
    ( 
     chef_id     NUMBER (3)  NOT NULL , 
     booking_id  NUMBER (7)  NOT NULL , 
     is_headchef CHAR (1 CHAR) 
    ) 
;

ALTER TABLE BOOKING_CHEF 
    ADD 
    CHECK (is_headchef IN ('N', 'Y')) 
;

COMMENT ON COLUMN BOOKING_CHEF.chef_id IS 'unique identifier of chef (up to 3 digit)' 
;

COMMENT ON COLUMN BOOKING_CHEF.booking_id IS 'A booking ID consisting of 7 digits (surrogate key)' 
;

COMMENT ON COLUMN BOOKING_CHEF.is_headchef IS 'indicates if a chef is head chef (Y-Yes, N-No)
' 
;

ALTER TABLE BOOKING_CHEF 
    ADD CONSTRAINT BOOKING_CHEF_PK PRIMARY KEY ( booking_id, chef_id ) ;

CREATE TABLE CHEF 
    ( 
     chef_id      NUMBER (3)  NOT NULL , 
     chef_name    VARCHAR2 (50)  NOT NULL , 
     chef_contact CHAR (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CHEF.chef_id IS 'unique identifier of chef (up to 3 digit)' 
;

COMMENT ON COLUMN CHEF.chef_name IS 'name of chef (up to 50 characters)' 
;

COMMENT ON COLUMN CHEF.chef_contact IS 'contact number of chef (10 digit phone number)' 
;

ALTER TABLE CHEF 
    ADD CONSTRAINT CHEF_PK PRIMARY KEY ( chef_id ) ;

CREATE TABLE CUISINE 
    ( 
     cuisine_type       VARCHAR2 (20)  NOT NULL , 
     cuisine_rate_guest NUMBER (5,2)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CUISINE.cuisine_type IS 'Type of cuisine - up to 20 characters' 
;

COMMENT ON COLUMN CUISINE.cuisine_rate_guest IS 'cuisine charge per guest in dollars (up to $999.99)' 
;

ALTER TABLE CUISINE 
    ADD CONSTRAINT CUISINE_PK PRIMARY KEY ( cuisine_type ) ;

CREATE TABLE CUSTOMER 
    ( 
     cust_id       NUMBER (7)  NOT NULL , 
     cust_name     VARCHAR2 (50)  NOT NULL , 
     cust_address  VARCHAR2 (50)  NOT NULL , 
     cust_contact  CHAR (10)  NOT NULL , 
     cust_business VARCHAR2 (50) 
    ) 
;

COMMENT ON COLUMN CUSTOMER.cust_id IS 'unique identifier of customer (7 digit)' 
;

COMMENT ON COLUMN CUSTOMER.cust_name IS 'name of customer (up to 50 characters)' 
;

COMMENT ON COLUMN CUSTOMER.cust_address IS 'customer address (up to 50 characters)' 
;

COMMENT ON COLUMN CUSTOMER.cust_contact IS 'customer contact number (10 digit phone number)' 
;

COMMENT ON COLUMN CUSTOMER.cust_business IS 'customer business name (up to 50 characters)' 
;

ALTER TABLE CUSTOMER 
    ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY ( cust_id ) ;

CREATE TABLE DECOR_THEME 
    ( 
     decor_theme_name VARCHAR2 (20)  NOT NULL 
    ) 
;

COMMENT ON COLUMN DECOR_THEME.decor_theme_name IS 'name of decoration theme (up to 20 letters)' 
;

ALTER TABLE DECOR_THEME 
    ADD CONSTRAINT DECOR_THEME_PK PRIMARY KEY ( decor_theme_name ) ;

CREATE TABLE EVALUATION 
    ( 
     eval_id       NUMBER (7)  NOT NULL , 
     room_id       NUMBER (7)  NOT NULL , 
     eval_date     DATE  NOT NULL , 
     chef_id       NUMBER (3)  NOT NULL , 
     eval_approval CHAR (1)  NOT NULL , 
     eval_comment  VARCHAR2 (200) 
    ) 
;

ALTER TABLE EVALUATION 
    ADD 
    CHECK (eval_approval IN ('N', 'Y')) 
;

COMMENT ON COLUMN EVALUATION.eval_id IS '7 digit evaluation identification number (surrogate key)' 
;

COMMENT ON COLUMN EVALUATION.room_id IS 'unique identifier of function room (up to 7 digits)' 
;

COMMENT ON COLUMN EVALUATION.eval_date IS 'evaluation date' 
;

COMMENT ON COLUMN EVALUATION.chef_id IS 'unique identifier of chef (up to 3 digit)' 
;

COMMENT ON COLUMN EVALUATION.eval_approval IS 'indicates whether the room is approved for use (Y-Yes or N-No)' 
;

COMMENT ON COLUMN EVALUATION.eval_comment IS 'optional evaluation comment (up to 200 characters)' 
;

ALTER TABLE EVALUATION 
    ADD CONSTRAINT EVALUATION_PK PRIMARY KEY ( eval_id ) ;

ALTER TABLE EVALUATION 
    ADD CONSTRAINT eval_UQ UNIQUE ( room_id , eval_date ) ;

CREATE TABLE MAINTENANCE 
    ( 
     eval_id           NUMBER (7)  NOT NULL , 
     mainte_start_date DATE  NOT NULL , 
     mainte_end_date   DATE 
    ) 
;

COMMENT ON COLUMN MAINTENANCE.eval_id IS '7 digit evaluation identification number (surrogate key)' 
;

COMMENT ON COLUMN MAINTENANCE.mainte_start_date IS 'Start date of maintenance' 
;

COMMENT ON COLUMN MAINTENANCE.mainte_end_date IS 'End date of maintenance' 
;

ALTER TABLE MAINTENANCE 
    ADD CONSTRAINT MAINTENANCE_PK PRIMARY KEY ( eval_id, mainte_start_date ) ;

CREATE TABLE ROOM 
    ( 
     room_id          NUMBER (7)  NOT NULL , 
     room_name        VARCHAR2 (50)  NOT NULL , 
     room_address     VARCHAR2 (50)  NOT NULL , 
     room_has_kitchen CHAR (1)  NOT NULL , 
     room_capacity    NUMBER (4)  NOT NULL , 
     room_rate_hour   NUMBER (5,2)  NOT NULL , 
     room_parking     CHAR (1)  NOT NULL 
    ) 
;

ALTER TABLE ROOM 
    ADD 
    CHECK (room_has_kitchen IN ('N', 'Y')) 
;

ALTER TABLE ROOM 
    ADD 
    CHECK (room_parking IN ('N', 'Y')) 
;

COMMENT ON COLUMN ROOM.room_id IS 'unique identifier of function room (up to 7 digits)' 
;

COMMENT ON COLUMN ROOM.room_name IS 'name of function room (up to 50 characters)' 
;

COMMENT ON COLUMN ROOM.room_address IS 'address of function room (up to 50 characters)' 
;

COMMENT ON COLUMN ROOM.room_has_kitchen IS 'indicates whether the function room has a kitchen (Y-Yes or N-No)' 
;

COMMENT ON COLUMN ROOM.room_capacity IS 'capacity of function room (up to 9999)' 
;

COMMENT ON COLUMN ROOM.room_rate_hour IS 'hourly rate of function room in dollors (up to $999.99)' 
;

COMMENT ON COLUMN ROOM.room_parking IS 'indicates if on-site parking is available (Y- Yes or N- No)' 
;

ALTER TABLE ROOM 
    ADD CONSTRAINT ROOM_PK PRIMARY KEY ( room_id ) ;

CREATE TABLE ROOM_CHARGE_HISTORY 
    ( 
     room_id                 NUMBER (7)  NOT NULL , 
     book_datetime_record    DATE  NOT NULL , 
     room_hourly_rate_record NUMBER (5,2)  NOT NULL 
    ) 
;

COMMENT ON COLUMN ROOM_CHARGE_HISTORY.room_id IS 'unique identifier of function room (up to 7 digits)' 
;

COMMENT ON COLUMN ROOM_CHARGE_HISTORY.book_datetime_record IS 'Date and time of a specific past booking ' 
;

COMMENT ON COLUMN ROOM_CHARGE_HISTORY.room_hourly_rate_record IS 'hourly room rate at the time of specific booking in dollors (up to $999.99)' 
;

ALTER TABLE ROOM_CHARGE_HISTORY 
    ADD CONSTRAINT ROOM_CHARGE_HISTORY_PK PRIMARY KEY ( book_datetime_record, room_id ) ;

CREATE TABLE SPECIALITY 
    ( 
     chef_id               NUMBER (3)  NOT NULL , 
     cuisine_type          VARCHAR2 (20)  NOT NULL , 
     speciality_start_year CHAR (4 CHAR)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SPECIALITY.chef_id IS 'unique identifier of chef (up to 3 digit)' 
;

COMMENT ON COLUMN SPECIALITY.cuisine_type IS 'Type of cuisine - up to 20 characters' 
;

COMMENT ON COLUMN SPECIALITY.speciality_start_year IS 'The year a chef started specialisation in a cuisine
(years of experience can be derived from this attribute)' 
;

ALTER TABLE SPECIALITY 
    ADD CONSTRAINT SPECIALITY_PK PRIMARY KEY ( chef_id, cuisine_type ) ;

ALTER TABLE BOOKING_CHEF 
    ADD CONSTRAINT book_chef_fk FOREIGN KEY 
    ( 
     booking_id
    ) 
    REFERENCES BOOKING 
    ( 
     booking_id
    ) 
;

ALTER TABLE BOOKING_CHEF 
    ADD CONSTRAINT chef_book_fk FOREIGN KEY 
    ( 
     chef_id
    ) 
    REFERENCES CHEF 
    ( 
     chef_id
    ) 
;

ALTER TABLE EVALUATION 
    ADD CONSTRAINT chef_eval_fk FOREIGN KEY 
    ( 
     chef_id
    ) 
    REFERENCES CHEF 
    ( 
     chef_id
    ) 
;

ALTER TABLE SPECIALITY 
    ADD CONSTRAINT CHEF_SPECIALITY_FK FOREIGN KEY 
    ( 
     chef_id
    ) 
    REFERENCES CHEF 
    ( 
     chef_id
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT cuisine_book_fk FOREIGN KEY 
    ( 
     cuisine_type
    ) 
    REFERENCES CUISINE 
    ( 
     cuisine_type
    ) 
;

ALTER TABLE SPECIALITY 
    ADD CONSTRAINT CUISINE_SPECIALITY_FK FOREIGN KEY 
    ( 
     cuisine_type
    ) 
    REFERENCES CUISINE 
    ( 
     cuisine_type
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT cust_book_fk FOREIGN KEY 
    ( 
     cust_id
    ) 
    REFERENCES CUSTOMER 
    ( 
     cust_id
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT decor_book_fk FOREIGN KEY 
    ( 
     decor_theme_name
    ) 
    REFERENCES DECOR_THEME 
    ( 
     decor_theme_name
    ) 
;

ALTER TABLE MAINTENANCE 
    ADD CONSTRAINT eval_mainte_fk FOREIGN KEY 
    ( 
     eval_id
    ) 
    REFERENCES EVALUATION 
    ( 
     eval_id
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT room_book_fk FOREIGN KEY 
    ( 
     room_id
    ) 
    REFERENCES ROOM 
    ( 
     room_id
    ) 
;

ALTER TABLE EVALUATION 
    ADD CONSTRAINT room_evel_fk FOREIGN KEY 
    ( 
     room_id
    ) 
    REFERENCES ROOM 
    ( 
     room_id
    ) 
;

ALTER TABLE ROOM_CHARGE_HISTORY 
    ADD CONSTRAINT room_room_charge_fk FOREIGN KEY 
    ( 
     room_id
    ) 
    REFERENCES ROOM 
    ( 
     room_id
    ) 
;


SPOOL off
set echo off


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             30
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
